source 'https://rubygems.org'

gem 'rails', '4.1.4'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

gem 'active_model_serializers'

gem 'rubocop', require: false

gem 'postgres_ext-serializers'


# To use ActiveModel has_secure_password
gem 'bcrypt'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
